# ysp-iommu-debug (generated by build-armbian-deb.sh)
#
# Armbian EXTENSION that enables the IOMMU/DMA debug observability options for
# RK3588 forward-port DEBUG builds. build-armbian-deb.sh copies this to
# $ARMBIAN_BUILD/userpatches/extensions/ysp-iommu-debug.sh when IOMMU_DEBUG=yes
# (and removes it otherwise), and passes ENABLE_EXTENSIONS=ysp-iommu-debug on the
# compile.sh command line so the extension manager actually loads it.
#
# WHY AN EXTENSION AND NOT lib.config: Armbian sources userpatches/lib.config
# AFTER the extension manager has already initialized, so hook functions defined
# there are never registered ("wishful hooking" -- see
# lib/functions/configuration/main-config.sh). Extension files in
# userpatches/extensions/, enabled via ENABLE_EXTENSIONS, are sourced during
# extension-manager init, so their custom_kernel_config__* hooks DO run.
#
# It is the build-wired equivalent of kconfig-debug.fragment. custom_kernel_config
# runs after the base .config is put in place and before `make olddefconfig` (see
# lib/functions/compilation/kernel-config.sh:119), so olddefconfig resolves any
# dependencies/selects afterwards. Debug-only; do not ship these debs.
#
# Usage / interpretation of the resulting signals: kernel-drivers/tests/IOMMU-FUZZING.md

function custom_kernel_config__ysp_iommu_debug() {
	# Register intent for artifact/config-cache hashing. This hook is called
	# twice (once without a .config in place), and the hash must be contributed
	# in both phases, so do it unconditionally before the .config guard.
	kernel_config_modifying_hashes+=("ysp-iommu-debug:DMA_API_DEBUG+KALLSYMS_ALL+IOMMU_DEBUGFS")

	# kernel_config_set_* run ./scripts/config, which needs a .config present.
	[[ -f .config ]] || return 0

	display_alert "ysp: enabling IOMMU/DMA debug kernel options" "iommu-debug" "info"

	# Cross-master DMA-API auditing: unbalanced map/unmap, wrong-device sync,
	# leaks -> printed as 'DMA-API:' in dmesg. Highest-value debug flag.
	kernel_config_set_y DMA_API_DEBUG
	# Full symbol table -> static RGA userptr-IOMMU / IOMMU helpers become kprobe-able.
	kernel_config_set_y KALLSYMS_ALL
	# Generic per-domain IOMMU debugfs.
	kernel_config_set_y IOMMU_DEBUGFS
	# Tracing substrate (usually already =y; pinned so a reconfigure keeps them).
	kernel_config_set_y FTRACE
	kernel_config_set_y KPROBES
	# KUnit stays modular for the optional RGA userptr-IOMMU fail-closed unit module.
	kernel_config_set_m KUNIT
}
