# SPDX-FileCopyrightText: 2026 Yi Ding
# SPDX-License-Identifier: GPL-2.0-only
# rk3588-vcodec DKMS — out-of-tree build of the vendor MPP + RGA drivers.
# Kbuild (this file) takes precedence over any Makefile in the same dir.
obj-m += mpp/
obj-m += rga3/
